CREATE TABLE IF NOT EXISTS `VaiTro` (
	`MaVT` VARCHAR(255) NOT NULL UNIQUE,
	`TenVaiTro` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`MaVT`)
);


CREATE TABLE IF NOT EXISTS `Khoa` (
	`MaKhoa` VARCHAR(255) NOT NULL UNIQUE,
	`TenKhoa` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`MaKhoa`)
);


CREATE TABLE IF NOT EXISTS `Lop` (
	`MaLop` VARCHAR(255) NOT NULL UNIQUE,
	`TenLop` VARCHAR(255),
	PRIMARY KEY(`MaLop`)
);

CREATE TABLE IF NOT EXISTS `NhomPhong` (
	`MaNhom` VARCHAR(255) NOT NULL UNIQUE,
	`TenNhom` VARCHAR(255),
	PRIMARY KEY(`MaNhom`)
);

CREATE TABLE IF NOT EXISTS `TrangThaiPhong` (
	`MaTTP` VARCHAR(255) NOT NULL UNIQUE,
	`TenTTP` VARCHAR(255),
	PRIMARY KEY(`MaTTP`)
);

CREATE TABLE IF NOT EXISTS `TrangThaiThietBi` (
	`MaTTTB` VARCHAR(255) NOT NULL UNIQUE,
	`TenTTTB` VARCHAR(255),
	PRIMARY KEY(`MaTTTB`)
);


CREATE TABLE IF NOT EXISTS `Loai` (
	`MaLoai` VARCHAR(255) NOT NULL UNIQUE,
	`TenLoai` VARCHAR(255),
	`SoLuong` INTEGER,
	PRIMARY KEY(`MaLoai`)
);


CREATE TABLE IF NOT EXISTS `TrangThaiPhieuMuon` (
	`MaTTPM` VARCHAR(255) NOT NULL UNIQUE,
	`TenTTPM` VARCHAR(255),
	PRIMARY KEY(`MaTTPM`)
);


CREATE TABLE IF NOT EXISTS `NguoiDung` (
	`MaND` VARCHAR(255) NOT NULL UNIQUE,
	`MaVT` VARCHAR(255) NOT NULL,
	`Ho` VARCHAR(255),
	`Ten` VARCHAR(255),
	`Email` VARCHAR(255),
	`MatKhau` VARCHAR(255),
	`Anh` VARCHAR(255),
	`Sdt` VARCHAR(255),
	`NgaySinh` DATE,
	`GioiTinh` TINYINT,
	`DiaChi` VARCHAR(255),
	`MaKhoa` VARCHAR(255) NOT NULL,
	`MaLop` VARCHAR(255) NOT NULL,
	`NgayTao` DATETIME,
	PRIMARY KEY(`MaND`)
);


CREATE TABLE IF NOT EXISTS `Phong` (
	`MaPhong` VARCHAR(255) NOT NULL UNIQUE,
	`TenPhong` VARCHAR(255),
	`MaNhom` VARCHAR(255) NOT NULL,
	`MaTrangThai` VARCHAR(255) NOT NULL,
	`SucChua` INTEGER,
	PRIMARY KEY(`MaPhong`)
);


CREATE TABLE IF NOT EXISTS `ThietBi` (
	`MaThietBi` VARCHAR(255) NOT NULL UNIQUE,
	`TenThietBi` VARCHAR(255),
	`MaLoai` VARCHAR(255) NOT NULL,
	`MaTTTB` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`MaThietBi`)
);


CREATE TABLE IF NOT EXISTS `ThietBi_Phong` (
	`MaPhong` VARCHAR(255) NOT NULL,
	`MaThietBi` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`MaPhong`, `MaThietBi`)
);


CREATE TABLE IF NOT EXISTS `PhieuMuon` (
	`MaPhieu` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`MaPhong` VARCHAR(255) NOT NULL,
	`MaND` VARCHAR(255) NOT NULL,
	`MaTTPM` VARCHAR(255) NOT NULL,
	`MucDich` VARCHAR(255),
	`NgayBD` DATE,
	`NgayKT` DATE,
	PRIMARY KEY(`MaPhieu`)
);


CREATE TABLE IF NOT EXISTS `TietHoc` (
	`MaTiet` VARCHAR(255) NOT NULL UNIQUE,
	`TenTiet` VARCHAR(255),
	`GioBD` TIME,
	`GioKT` TIME,
	PRIMARY KEY(`MaTiet`)
);


CREATE TABLE IF NOT EXISTS `ThoiGian` (
	`MaPhieu` INTEGER NOT NULL,
	`MaTiet` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`MaPhieu`, `MaTiet`)
);


ALTER TABLE `NguoiDung`
ADD FOREIGN KEY(`MaVT`) REFERENCES `VaiTro`(`MaVT`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `NguoiDung`
ADD FOREIGN KEY(`MaKhoa`) REFERENCES `Khoa`(`MaKhoa`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `NguoiDung`
ADD FOREIGN KEY(`MaLop`) REFERENCES `Lop`(`MaLop`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Phong`
ADD FOREIGN KEY(`MaNhom`) REFERENCES `NhomPhong`(`MaNhom`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Phong`
ADD FOREIGN KEY(`MaTrangThai`) REFERENCES `TrangThaiPhong`(`MaTTP`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ThietBi`
ADD FOREIGN KEY(`MaTTTB`) REFERENCES `TrangThaiThietBi`(`MaTTTB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ThietBi_Phong`
ADD FOREIGN KEY(`MaPhong`) REFERENCES `Phong`(`MaPhong`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ThietBi_Phong`
ADD FOREIGN KEY(`MaThietBi`) REFERENCES `ThietBi`(`MaThietBi`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ThietBi`
ADD FOREIGN KEY(`MaLoai`) REFERENCES `Loai`(`MaLoai`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PhieuMuon`
ADD FOREIGN KEY(`MaPhong`) REFERENCES `Phong`(`MaPhong`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ThoiGian`
ADD FOREIGN KEY(`MaTiet`) REFERENCES `TietHoc`(`MaTiet`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PhieuMuon`
ADD FOREIGN KEY(`MaND`) REFERENCES `NguoiDung`(`MaND`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ThoiGian`
ADD FOREIGN KEY(`MaPhieu`) REFERENCES `PhieuMuon`(`MaPhieu`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PhieuMuon`
ADD FOREIGN KEY(`MaTTPM`) REFERENCES `TrangThaiPhieuMuon`(`MaTTPM`)
ON UPDATE NO ACTION ON DELETE NO ACTION;